apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obs-engine-data-pvc
  namespace: kube-observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obs-engine-be-auth-data-pvc
  namespace: kube-observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
