apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-log-agent-config
  namespace: kube-observability
data:
  LOKI_URL: "http://loki-loki-distributed-query-frontend:3100" # !!! THAY THẾ BẰNG URL LOKI CỦA BẠN !!!
  SCAN_INTERVAL_SECONDS: "30"
  LOKI_SCAN_RANGE_MINUTES: "1"
  LOKI_DETAIL_LOG_RANGE_MINUTES: "30"
  LOKI_QUERY_LIMIT: "500"
  # --- BỎ K8S_NAMESPACES ---
  # K8S_NAMESPACES: "kube-system,app-infra,alfinac-bee-logistics"
  # --- THÊM EXCLUDED_NAMESPACES (Tùy chọn) ---
  # Liệt kê các namespace không muốn quét, cách nhau bởi dấu phẩy
  # Ví dụ: loại bỏ các namespace hệ thống ít quan trọng
  EXCLUDED_NAMESPACES: "kube-node-lease,kube-public"
  # --- KẾT THÚC THAY ĐỔI ---
  LOKI_SCAN_MIN_LEVEL: "WARNING"
  ALERT_SEVERITY_LEVELS: "WARNING,ERROR,CRITICAL"
  RESTART_COUNT_THRESHOLD: "5"
  GEMINI_MODEL_NAME: "gemini-1.5-flash" # Vẫn giữ nếu có thể fallback
  DB_PATH: "/data/agent_stats.db"
  STATS_UPDATE_INTERVAL_SECONDS: "300"
  LOCAL_GEMINI_ENDPOINT: "http://gemini-local-svc.kube-observability.svc.cluster.local:5000/generate"
  USE_LOCAL_MODEL: "false" # Đang dùng Gemini thật
  PROMPT_TEMPLATE: |
    Phân tích tình huống của pod Kubernetes '{namespace}/{pod_name}'.
    **Ưu tiên xem xét ngữ cảnh Kubernetes** được cung cấp dưới đây vì nó có thể là lý do chính bạn được gọi.
    Kết hợp với các dòng log sau đây (nếu có) để đưa ra phân tích đầy đủ.
    Xác định mức độ nghiêm trọng tổng thể (chọn một: INFO, WARNING, ERROR, CRITICAL).
    Nếu mức độ nghiêm trọng là WARNING, ERROR hoặc CRITICAL, hãy cung cấp một bản tóm tắt ngắn gọn (1-2 câu) bằng **tiếng Việt** giải thích vấn đề cốt lõi, kết hợp thông tin từ ngữ cảnh và log.
    Tập trung vào các tác động tiềm ẩn.

    Ngữ cảnh Kubernetes:
    --- START CONTEXT ---
    {k8s_context}
    --- END CONTEXT ---

    Các dòng log (có thể không có):
    --- START LOGS ---
    {log_text}
    --- END LOGS ---

    Chỉ trả lời bằng định dạng JSON với các khóa "severity" và "summary". Ví dụ: {{"severity": "CRITICAL", "summary": "Pod 'kube-system/oomkill-test-pod' bị Terminated với lý do OOMKilled và có Event OOMKilled gần đây. Cần kiểm tra giới hạn bộ nhớ và code ứng dụng."}}
