apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-log-agent-config
  namespace: kube-observability
data:
  LOKI_URL: "http://loki-loki-distributed-query-frontend:3100"
  SCAN_INTERVAL_SECONDS: "30"
  LOKI_SCAN_RANGE_MINUTES: "1"
  LOKI_DETAIL_LOG_RANGE_MINUTES: "30"
  LOKI_QUERY_LIMIT: "500"
  K8S_NAMESPACES: "kube-system,app-infra,alfinac-bee-logistics"
  LOKI_SCAN_MIN_LEVEL: "WARNING"
  ALERT_SEVERITY_LEVELS: "WARNING,ERROR,CRITICAL"
  RESTART_COUNT_THRESHOLD: "5"
  # GEMINI_MODEL_NAME: "gemini-1.5-flash" # Có thể bỏ hoặc giữ nếu muốn fallback
  DB_PATH: "/data/agent_stats.db"
  STATS_UPDATE_INTERVAL_SECONDS: "300"
  # --- THÊM CẤU HÌNH MỚI ---
  # Để trống hoặc không đặt biến này nếu muốn dùng Gemini API thật
  LOCAL_GEMINI_ENDPOINT: "http://gemini-local-svc.kube-observability.svc.cluster.local:5000/generate"
  # --- KẾT THÚC THÊM CẤU HÌNH MỚI ---