apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-log-agent-config
  namespace: kube-observability # Đảm bảo namespace này đúng với môi trường của bạn
data:
  # --- Loki Configuration ---
  LOKI_URL: "http://loki-loki-distributed-query-frontend.loki.svc.cluster.local:3100" # !!! THAY THẾ BẰNG URL LOKI CỦA BẠN !!!
  LOKI_SCAN_RANGE_MINUTES: "1" # Khoảng thời gian quét log nhanh (phút)
  LOKI_DETAIL_LOG_RANGE_MINUTES: "30" # Khoảng thời gian lấy log chi tiết khi điều tra (phút)
  LOKI_QUERY_LIMIT: "500" # Giới hạn số dòng log khi query chi tiết
  LOKI_SCAN_MIN_LEVEL: "INFO" # Mức log tối thiểu để quét Loki ban đầu (DEBUG, INFO, WARNING, ERROR, CRITICAL)

  # --- Agent Behavior ---
  SCAN_INTERVAL_SECONDS: "30" # Tần suất quét (giây)
  STATS_UPDATE_INTERVAL_SECONDS: "300" # Tần suất cập nhật DB thống kê (giây)
  NAMESPACE_REFRESH_INTERVAL_SECONDS: "3600" # Tần suất làm mới danh sách namespace từ K8s (giây, 1 giờ)

  # --- Kubernetes Monitoring ---
  EXCLUDED_NAMESPACES: "kube-node-lease,kube-public" # Các namespace loại trừ khỏi quét
  DEFAULT_MONITORED_NAMESPACES: "kube-system,default" # Namespace mặc định nếu không có cấu hình trong DB
  RESTART_COUNT_THRESHOLD: "5" # Ngưỡng restart container để coi là sự cố

  # --- AI Analysis Configuration ---
  GEMINI_MODEL_NAME: "gemini-1.5-flash" # Tên model Gemini
  USE_LOCAL_MODEL: "false" # Đặt thành "true" nếu muốn dùng model local thay vì Gemini API
  LOCAL_GEMINI_ENDPOINT: "" # URL của endpoint model local (chỉ cần nếu USE_LOCAL_MODEL=true)

  # v1.0.6: Updated Prompt Template
  PROMPT_TEMPLATE: |
    Phân tích tình huống của pod Kubernetes '{namespace}/{pod_name}'.
    **Ưu tiên xem xét ngữ cảnh Kubernetes** được cung cấp dưới đây vì nó có thể là lý do chính bạn được gọi.
    Kết hợp với các dòng log sau đây (nếu có) để đưa ra phân tích đầy đủ.

    1.  Xác định mức độ nghiêm trọng tổng thể (chọn một: INFO, WARNING, ERROR, CRITICAL).
    2.  Nếu mức độ nghiêm trọng là WARNING, ERROR hoặc CRITICAL:
        a. Cung cấp một bản tóm tắt ngắn gọn (1-2 câu) bằng **tiếng Việt** giải thích vấn đề cốt lõi.
        b. Đề xuất **nguyên nhân gốc có thể xảy ra** (potential root causes) (ngắn gọn, dạng gạch đầu dòng nếu có nhiều).
        c. Đề xuất các **bước khắc phục sự cố** (suggested troubleshooting steps) (ngắn gọn, dạng gạch đầu dòng).

    Ngữ cảnh Kubernetes:
    --- START CONTEXT ---
    {k8s_context}
    --- END CONTEXT ---

    Các dòng log (có thể không có):
    --- START LOGS ---
    {log_text}
    --- END LOGS ---

    Chỉ trả lời bằng định dạng JSON với các khóa "severity", "summary", "root_cause", và "troubleshooting_steps".
    Ví dụ:
    {{
      "severity": "CRITICAL",
      "summary": "Pod 'kube-system/oomkill-pod' bị Terminated với lý do OOMKilled.",
      "root_cause": "- Giới hạn bộ nhớ (memory limit) quá thấp.\n- Ứng dụng bị rò rỉ bộ nhớ (memory leak).",
      "troubleshooting_steps": "- Tăng memory limit cho pod.\n- Phân tích memory profile của ứng dụng.\n- Kiểm tra lại logic cấp phát/giải phóng bộ nhớ trong code."
    }}

  # --- Alerting Configuration ---
  ALERT_SEVERITY_LEVELS: "INFO,WARNING,ERROR,CRITICAL" # Các mức độ sẽ gửi cảnh báo Telegram

  # v1.0.6: Added configurable Telegram Alert Template
  # Các placeholder có sẵn: {pod_key}, {severity}, {summary}, {root_cause}, {troubleshooting_steps}, {initial_reasons}, {alert_time}, {sample_logs}
  TELEGRAM_ALERT_TEMPLATE: |
    🚨 *Cảnh báo K8s/Log (Pod: {pod_key})* 🚨
    *Mức độ:* `{severity}`
    *Tóm tắt:* {summary}
    *Nguyên nhân gốc có thể:*
    {root_cause}
    *Đề xuất khắc phục:*
    {troubleshooting_steps}
    *Lý do phát hiện ban đầu:* {initial_reasons}
    *Thời gian phát hiện:* `{alert_time}`
    *Log mẫu (nếu có):*
    {sample_logs}

    _Vui lòng kiểm tra chi tiết trên dashboard hoặc Loki/Kubernetes._

  # --- Database Path ---
  DB_PATH: "/data/agent_stats.db" # Đường dẫn tới file SQLite trên PVC

