apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-log-agent-config
  namespace: kube-observability
data:
  # Sửa dòng này: Bỏ dấu nháy kép bao quanh
  ALERT_SEVERITY_LEVELS: WARNING,ERROR,CRITICAL
  GEMINI_MODEL_NAME: gemini-1.5-flash
  K8S_NAMESPACES: kube-system,app-infra,alfinac-bee-logistics
  LOKI_QUERY_LIMIT: '1000'
  LOKI_QUERY_RANGE_MINUTES: '5'
  LOKI_URL: http://loki-loki-distributed-query-frontend:3100
  # Đảm bảo dòng này đúng
  MIN_LOG_LEVEL_FOR_GEMINI: WARNING
  QUERY_INTERVAL_SECONDS: '30'