apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-log-agent
  namespace: kube-observability
  labels:
    app: k8s-log-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-log-agent
  template:
    metadata:
      labels:
        app: k8s-log-agent
    spec:
      serviceAccountName: k8s-log-agent-sa
      containers:
      - name: agent
        # !!! THAY THẾ BẰNG TÊN IMAGE CỦA BẠN (ví dụ: v0.7) !!!
        image: lechaukha12/ai-agent1:v1.0.2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: k8s-log-agent-config
          - secretRef:
              name: k8s-log-agent-secret
        # --- BẮT ĐẦU THAY ĐỔI: Thêm biến môi trường TZ ---
        env:
        - name: TZ
          value: Asia/Ho_Chi_Minh # Đặt múi giờ cho container
        # --- KẾT THÚC THAY ĐỔI ---
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "750m"
            memory: "768Mi"
      securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
