apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-log-agent # Đổi tên Deployment
  namespace: kube-observability # Namespace mới
  labels:
    app: k8s-log-agent # Đổi label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-log-agent # Đổi label selector
  template:
    metadata:
      labels:
        app: k8s-log-agent # Đổi label pod
    spec:
      serviceAccountName: k8s-log-agent-sa # Sử dụng Service Account đã đổi tên
      containers:
      - name: agent
        # !!! THAY THẾ BẰNG TÊN IMAGE CỦA BẠN (ví dụ: v0.6) !!!
        image: your-dockerhub-username/k8s-log-agent:v1.0 # Giữ tên image nhưng có thể tăng version
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              # Giữ nguyên tên ConfigMap hoặc đổi nếu muốn (ví dụ: k8s-log-agent-config)
              name: k8s-log-agent-config
          - secretRef:
              # Giữ nguyên tên Secret hoặc đổi nếu muốn (ví dụ: k8s-log-agent-secret)
              name: k8s-log-agent-secret
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "750m"
            memory: "768Mi"
      securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
