apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-log-agent # Tên Deployment
  namespace: kube-observability # Namespace mới
  labels:
    app: k8s-log-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-log-agent
  template:
    metadata:
      labels:
        app: k8s-log-agent
    spec:
      serviceAccountName: k8s-log-agent-sa # Sử dụng Service Account
      containers:
      - name: agent
        # !!! THAY THẾ BẰNG TÊN IMAGE v1.0.4 CỦA BẠN !!!
        image: your-dockerhub-username/k8s-log-agent:v1.0.4
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: k8s-log-agent-config
          - secretRef:
              name: k8s-log-agent-secret
        env:
        - name: TZ
          value: Asia/Ho_Chi_Minh # Đặt múi giờ
        volumeMounts:
        - name: agent-data # Tên volume mount
          mountPath: /data   # Thư mục mount PV để lưu DB
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "750m"
            memory: "768Mi"
      securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
      volumes:
      - name: agent-data # Tên volume
        persistentVolumeClaim:
          claimName: k8s-log-agent-data-pvc # Tên PVC đã tạo
