apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-log-agent
  namespace: kube-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-log-agent
    spec:
      volumes:
        - name: agent-data
          persistentVolumeClaim:
            claimName: k8s-log-agent-data-pvc
      containers:
        - name: agent
          image: codebuild.alfinac.com:4444/library/ai-agent1:v1.0.5
          envFrom:
            - configMapRef:
                name: k8s-log-agent-config
            - secretRef:
                name: k8s-log-agent-secret
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
          resources:
            limits:
              cpu: 750m
              memory: 768Mi
            requests:
              cpu: 150m
              memory: 256Mi
          volumeMounts:
            - name: agent-data
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: k8s-log-agent-sa
      serviceAccount: k8s-log-agent-sa
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
        fsGroup: 1001
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
