apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-log-agent
  namespace: kube-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-log-agent
  template:
    metadata:
      labels:
        app: k8s-log-agent
    spec:
      containers:
        - name: agent
          image: codebuild.alfinac.com:4444/library/ai-agent1:v1.0.7
          envFrom:
            - configMapRef:
                name: k8s-log-agent-config
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: K8S_CLUSTER_NAME
              value: "alfinac-k8s-cluster-1"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: k8s-log-agent-sa
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
