apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-local # Giữ tên deployment
  namespace: kube-observability
  labels:
    app: gemini-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini-local
  template:
    metadata:
      labels:
        app: gemini-local
    spec:
      containers:
      - name: model-server
        # !!! THAY THẾ BẰNG TÊN IMAGE MỚI (DistilBERT) !!!
        image: codebuild.alfinac.com:4444/library/gemini-local-service:v1.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MODEL_PATH
          value: "/app/local_model"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30 # Có thể giảm thời gian chờ load
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        # --- Điều chỉnh Resources cho DistilBERT ---
        resources:
          requests:
            cpu: "500m"  # Vẫn cần CPU khá
            memory: "1Gi" # Yêu cầu RAM có thể thấp hơn T5
          limits:
            cpu: "1"    # Giới hạn 1 CPU core
            memory: "2Gi" # Giới hạn 2GB RAM (Theo dõi và điều chỉnh)
      # nodeSelector:
      #   hardware: high-memory
