apiVersion: v1
kind: ServiceAccount
metadata:
  name: obs-engine-sa
  namespace: kube-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: obs-engine-cluster-reader
rules:
- apiGroups: [""] # Core API group
  resources: ["namespaces", "nodes", "events"]
  verbs: ["get", "list"]
- apiGroups: ["version"]
  resources: ["*"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: obs-engine-read-cluster-info
subjects:
- kind: ServiceAccount
  name: obs-engine-sa
  namespace: kube-observability
roleRef:
  kind: ClusterRole
  name: obs-engine-cluster-reader
  apiGroup: rbac.authorization.k8s.io
