apiVersion: v1
kind: ServiceAccount
metadata:
  name: obs-engine-sa
  namespace: kube-observability # Đảm bảo đúng namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Tên ClusterRole nên rõ ràng về quyền hạn
  name: obs-engine-namespace-reader
rules:
- apiGroups: [""] # Core API group
  resources: ["namespaces"]
  verbs: ["get", "list"] # Chỉ cần quyền đọc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: obs-engine-read-namespaces
subjects:
- kind: ServiceAccount
  name: obs-engine-sa          # Tên ServiceAccount đã tạo
  namespace: kube-observability # Namespace của ServiceAccount
roleRef:
  kind: ClusterRole
  name: obs-engine-namespace-reader # Tên ClusterRole đã tạo
  apiGroup: rbac.authorization.k8s.io
