apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-log-agent-sa # Đổi tên Service Account
  namespace: kube-observability # Đổi namespace của agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-log-agent-reader # Giữ tên cũ hoặc đổi nếu muốn
rules:
- apiGroups: [""] # Core API group
  # Thêm "namespaces" vào resources
  resources: ["pods", "nodes", "events", "namespaces"] # <<< Đã thêm namespaces
  # Giữ nguyên verbs chỉ đọc
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-log-agent-reader-binding
subjects:
- kind: ServiceAccount
  name: k8s-log-agent-sa
  namespace: kube-observability
roleRef:
  kind: ClusterRole
  name: k8s-log-agent-reader
  apiGroup: rbac.authorization.k8s.io
    