apiVersion: v1
kind: Secret
metadata:
  name: k8s-log-agent-secret
  namespace: kube-observability
type: Opaque
stringData:
  GEMINI_API_KEY: "AIzaSyCJsWeWVgf-Vr3vupzIa0VHV08rZfraVuo"
  TELEGRAM_BOT_TOKEN: "7990395050:AAEA-sDY6fmex8yJ2wmn6k29IE_DIlF5WQc"
  TELEGRAM_CHAT_ID: "-4749905362"